# Generated by Django 4.2.5 on 2023-10-01 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'admin_table',
            },
        ),
        migrations.CreateModel(
            name='Music',
            fields=[
                ('language', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('releaseyear', models.IntegerField()),
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('movie', models.CharField(max_length=100)),
                ('singer', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Podcasts',
            fields=[
                ('language', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('releaseyear', models.IntegerField()),
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('author', models.CharField(max_length=100)),
            ],
        ),
    ]
