# Generated by Django 4.2.5 on 2023-10-14 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_persons'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Persons',
        ),
    ]
