# Generated by Django 4.2.5 on 2023-10-14 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('language', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('releaseyear', models.IntegerField()),
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('movie', models.CharField(max_length=100)),
                ('singer', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Podcasts',
            fields=[
                ('language', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('releaseyear', models.IntegerField()),
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('author', models.CharField(max_length=100)),
            ],
        ),
    ]
