# Generated by Django 4.2.5 on 2023-11-04 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_music_podcasts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Musics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('music_id', models.IntegerField()),
                ('title', models.CharField(max_length=100)),
                ('singer', models.CharField(max_length=100)),
                ('music_director', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='music/images/')),
                ('audio_file', models.FileField(upload_to='music/audio/')),
            ],
        ),
    ]
