# Generated by Django 4.2.5 on 2023-11-04 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0003_musics'),
    ]

    operations = [
        migrations.AddField(
            model_name='musics',
            name='language',
            field=models.CharField(default='Telugu', max_length=100),
        ),
    ]
