# Generated by Django 4.2.5 on 2023-11-04 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0004_musics_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musics',
            name='language',
            field=models.CharField(max_length=100),
        ),
    ]
